# Generated by Django 3.2.6 on 2021-08-24 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('surename', models.CharField(max_length=250)),
                ('fathername', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250)),
                ('birthday', models.DateField()),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Author',
                'ordering': ['-birthday'],
            },
        ),
        migrations.CreateModel(
            name='Publishings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('write_date', models.DateField()),
                ('discription', models.CharField(max_length=4000)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='books/%y/%m/%d')),
                ('author_relative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='books.authors', verbose_name='author')),
                ('publishing_relative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='books.publishings', verbose_name='publishing')),
            ],
            options={
                'verbose_name': 'Books',
                'verbose_name_plural': 'Books',
                'ordering': ['name'],
            },
        ),
    ]
