# Generated by Django 3.2.6 on 2021-09-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210909_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=250)),
                ('review', models.CharField(max_length=3000)),
            ],
        ),
        migrations.AlterModelOptions(
            name='authors',
            options={'ordering': ['name'], 'verbose_name': 'Authors', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books/%y/%m/%d'),
        ),
    ]
