# Generated by Django 3.2.6 on 2021-09-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210909_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='discription',
            new_name='description',
        ),
    ]
